* part I -- Introduction (Different Trains and what the STEM Bandwagon might be)
** explanation of title (Range of Pathways for Artists? But this "Education")
The title Different Trains is intended as a reference--and tribute--to the Steve Reich piece of the same name.

In this case, I am drawing a comparison between a very 19th Century form of mobility and organization, on the one hand, and similarly large, top-down and potentially landscape-altering efforts to "enhance" our educational system, on the other.

So, on some level this would appear to be about education, and the many ways that educational reform is playing and may yet still play out in the 21st Century.

But in my proposal I asserted that these efforts, beyond their effect on educators in the arts and otherwise, are relevant more generally to practicing artists, as well.

And, by alluding to the fact that some of the trains that Reich evoked in his piece were indeed Auschwitz-bound, I imply that there are some "trains" or pathways for us in the 21st Century that involve drastic or nightmarish fates for artists. It may of course be hyperbole of a rather cheap or distasteful sort to suggest that there is a remote parallel to "After Auschwitz--no poetry" in "After Common Core, no NEA-funding" or something.

But in an era when so much power is dubious concentrated in the remote servers of companies with bland, simplistic mission statements like, "Don't Be Evil" or "Make the world more connected and open," it may be excusable to consider the darker implications of what is otherwise presented as "customer-driven" or just inevitable.
** context of education (leading to valorization of STEM--how is this threatening?)

The context I'd like to consider is, of course, right here, good ol' Earth, right now in 2018. More specifically, I'd like to situate us in that corner of Earth given over to "education," the idea that, superficially at least, explains the existence of these walls, these books, perhaps even these infernal machines, and indeed, our very presence here at this symposium.

# Dictionary definitions of "to educate" vary, but usually revolve around imparting "knowledge" or even just "information," Indeed, we are widely considered to be living in a "Information age." An age of "what." What is the most viewed YouTube video of all time? What's the most re-tweeted, liked, favorited, bookmarked, recommended...thing. What's on your mind, Will? What, what, what.

Do you think this is a good thing for artists? Is this a "good time to be an artist?" The sensible answer of course is that it depends. Which artists? Is it a good time to be a musician? Is it a good time to be a professional musician? Is is a good time to try to become a professional musician?
** ambiguity of simple questions about education and the arts 
What about these questions: Is it a good time to be a teacher? Is it a good time to be a computer programmer?

Now, these questions are moot, loaded, disingenuous, facile, unanswerable. And yet such questions are vitally important to young people figuring out how who they are, and what they are going to choose to do with their lives.

But their answers are ambiguous, "merely subjective," difficult to establish with any certainty.

Well, in the face of such uncertainty we can ask, well, what /do/ we know? According to one of the contributors to the National Research Council's /A Framework for K-12 Science Education/, we know that "science is the key to solving the world's most pressing challenges." [x3]

Now, perhaps that author would like to reconsider exactly how he or she chose to word that. But probably the main reason to do so would simply be to make his argument more palatable, not because he doubted its validity.

And it's precisely this matter of certainty vs. ambiguity that art is especially well-suited to address.
** So What "Is" science/STEM? And what does that have to do with art?
Now having raised the question of ambiguity and referenced a particular version of educational reform, that presented by the NRC, it comes time to briefly examine what is contained in these STEM prescriptions, and what that really might mean for artists. How could this turn out badly for artists, and for our society more generally?

* part II -- What is Meaning in Science? (why is this Monolithic Monoculture?)
** patterns vs. ambiguity
I'd like to come back to that, so please hold that favorite word of mine--ambiguity, or just "ambiguous"--in your head for a little bit.

Now, by so doing, you will be touching on another peculiar aspect of our age, which is the many demands placed on our attention during the course of an average day, when we are often required to suspend our awareness of one thing in order to devote ourselves to something else. The strain or cognitive cost of doing all this varies--keeping the word 'ambiguity' in mind hopefully won't be as hard as keeping the first 8 digits of the decimal representation of PI in your head 3.1415926 (...53589793...), which I'd also like you to do. Forgot already? Too bad. Should've been paying attention. No cheating. :)

Wouldn't it be easier if we had some way to compress that arbitrary information, this random sequence of digits (it is widely asserted that the digits of pi are randomly distributed, but this has never been proved--so do we know it or not?). It turns out that the writer Issac Asimov came up with a way to remember the first 15--"How I want a drink, alcoholic of course, after the heavy lectures involving quantum mechanics." Where the length of each word--3 letters in "how", 1 letter in "I", 4 letters in "want," etc.--gives the digit in question.
** Frameworks and NSF acronym (what is the gloss on Standards and Frameworks and ed reform?)
This particular mnemonic is, unfortunately, not part of the /Framework for K-12 Science Education/. But in general, our minds are pretty highly attuned to looking for, identifying and remembering patterns--even where they don't exist. Acronyms are everywhere in education, from ROYGBIV to HOMES. If you trust Wikipedia, which I will not require of you, METS was once an acronym for Mathematics, Engineering, Technology and Science. 

Now, as a longtime fan of a certain baseball team from New York City, I can tell you that this one resonates deeply with me. But for some reason, the director of the National Science Foundation expressed some "dislike" for this (presumably she was a Yankees fan).

And so now, whenever we want to think about education policy, which, you may not have been paying attention to the Betsy DeVos confirmation hearings (or heard of the Common Core or Bill and Melinda Gates or Google Education), is happening a lot these days, we have a more memorable, less NY-centric, biased, term. We have a great "what." Tidy, concise, rolls off the tongue--it's become almost a meme.
** The power of names and the inferences they make possible
I refuse to say it, just like I refuse to say the name of the head of the executive branch of U.S. Federal Government. POTUS. Works for me.

But what's the problem? What's in a name? Airy nothing a local habitation...

For many, it simply stands for a need to improve science education, a laudable goal for anyone whoever had to memorize the order of the colors on the visible spectrum by imagining a Mr. Biv, middle name unknown. Or for anyone who ever checked out of a math or science class because a "sink or swim" atmosphere pervaded the classroom, or worse, who was ever actively dissauded from persuing a rigorous course of study because of some unspoken preconceptions of what a real scientist looks like.

But there's more in a name--and to this name in particular--than just "local habitation." 

The power that comes with naming is, 


...

...

...
* part III -- Why Should We Be Concerned?
** What are some Current Trends and Concerns? (Because the litany)
Because technology increases, it adds options, possibilities, ways of arranging those possibilities.

Technology gives us the tools to manage complexity while also giving us more complexity.

But also because I'm trying to talk about so much. Because as I see it's all interrelated.
** the litany
The various motivations and approaches of educational reform movements

The increasing role of technology in our lives and in our pedagogy

The concomitant growth of techno skepticism

The rise of data-driven everything

The increase in computational power

The unfaltering ascent of STEM skills in our culture

The ever marginal role of the arts and musicianship specifically

The diminished value we place on things of limited practical (as opposed to cultural) utility

The precarious place of people in an age of automation

The limits of academia and scholarship to influence the larger culture

The compromises we make and those we avoid making in the midst of system with no one really in control

The alternative strands within the dominant strain of culture

The growth of a collaborative software culture

The fate of alternative organizational approaches

The metaphor of language

Our own fate as individuals, as a society, as a civilization, as a species, as a planet, as spiritual beings, as inheritors and as forbearers

The failure of the imagination that it all represents
** Move beyond the drawbacks

What it risks being, on some level, is a compendium, a complete list of the things it touches on. A clearinghouse for ideas and trends and  evidence and hypotheses. 

But I can't really do what I want simply by listing a bunch of "drawbacks to STEM," or doing some kind of cost-benefit analysis. I'm not offering some kind of refutation of an argument that we need better science education. This is just one person's nervous reaction to what I sense is happening, ans what i feel is missing, and what I believe is possible. So while limitations of space preclude me from offering any kind of fully spelled out alternative, a truly "different train"...

Instead I have to transition to what art is "good for," even though baldly stating this goes against my grain, and even on some level betrays what's most important about what I want to convey.
* part IV -- What Can We Do About it?
** the rapproachment with technology via the humanistic and literate
** how would three languages be a complement or a corrective
** how do you interweave languages? How do you use technology in a way that preserves freedom?
** Meanings in Art vs. Math and Science (What is Art About?)

So what I'll do is say that 
this is hard not just because I'm trying to be comprehensive, or trying to combine disparate things, or trying to talk and "program" at the same time. It's hard because...

what it "is" has something to do with the complicated relationship between "is" and "about." The distinctions between two ideas or categories these become illusory, I  believe, when discussing art within a context of reasoning, and practical utility and economic value. Its "is-ness" forms an "about" in a way that is unique to art. Or so I'd like to suggest. Or so I'm hoping to illustrate. Or so I'm hoping to achieve. (Gadamer is useful in this regard, this business of "is-ness.")

Its meaning can't be separated from the language in which it was communicated, with all that went along with the words I choose. This is in direct opposition to math, where the symbols and relationships between them are atemporal, inviolable, true regardless of the language that surrounded them, provided that the right context has been established. (Now this is no small proviso, but your stereotypical STEMmer is usually willing to take this for granted.)

The meaning of a scientific experiment, meanwhile, can always be translated. (The world would be a poorer place by far if understanding scientific knowledge demanded we all learn some kind of Esperanto.)

Doing so with art, however, always produces another related but different work of art, with its own distinct but related meaning. Newton's third law means the same thing no matter what language you  speak (but Shakespeare in German, or Rilke in English, is another beast entirely). Surely it would be foolish to deny the power in that. But just as surely we can question the refusal to admit of other ways of capturing truth.
** Low Utility of what Art Provides

Its is-ness is what it's about, here, today, with me standing up here, in a way that defies summarization, the neat encapsulation demanded of a hypothesis or a conclusion. Because what conclusion can you really draw about something that is about complicating the whole question of "what it is," except to say, it's complicated. Or I don't get it. Or it doesn't work, or doesn't effectively do what it purports to do. Or "everything is everything" and wow how very trippy that is. Or whatever conclusion you eventually 
or ultimately 
or one day reach and on another day are unable or unwilling to reach.

Now admittedly this is a much harder thing to accept as useful. As something that will increase the GDP or one's purchasing power, or get one into Connecticut College, or heigthen one's value on the job market. Or even as something that belongs on some curriculum somewhere.

** Double Language
Arts ability to communicate more than one thing at the same time, or at different times, needs defending and no science framework or design-by-committee academic standard is up to the task. "Article 4.1.a states ambiguity is powerful"

Art's ability to communicate more than one thing, in more than one language, this kind of irony or doubleness of what is spoken and what is meant, is unique to art (and natural language), and represents a powerful mode of reasoning and thinking and communicating. One that gives and refuses, that creates an experience for you but declines to explain it at the risk of over-explaining. At the risk of taking away your own contribution in your mind to what it "is." Something that, regardless of the number of SparkNotes books telling perplexed students what to regurgitate on test day, or little explanatory placards the curator or some historian provides, or scholarly journal abstracts with requisite keywords we provide,

cannot be exhausted, cannot be anticipated, and cannot be denied.

Research that can't be reproduced in a way that's good and totally at odds with what peer reviewed science demands.
** Defense of art as a way of thinking
I would argue that this ambiguity is a kind of thinking that the tidy scientific mode of experiencing the world can't accept, and by definition, can't provide. But it is no less important, for reasons I could try to articulate, enumerate, explicate. But I don't want to deny you that experience yourself.

So instead I wish to simply defend it. To argue that it is a way of thinking that must be defended now in an age ever more convinced that it knows what it needs to know. The best Art provides something you need to know, but that you don't "need." Try publishing that in a science journal.

... Don't need and that no one wants to pay for.

It's okay, it's good...If you walk away saying, I thought I knew what he/it meant while he was talking, but then when it was over, I couldn't really tell you what it was he was saying, or I thought he was saying. 

Together we will have done a job, collaborated on a real time meaning, that no algorithm can do for you. That any multiple choice question will fail to do justice to. 

And that should be celebrated. Art did its job, leaving you smarter and more confused, less certain and all the wiser for it.
* Extras
** Breathlessly anodyne                                   :ammerman:bigstory:
   :PROPERTIES:
   :CREATED:  [2018-01-13 Sat 05:42]
   :END:

 Frameworks and methodologies and rubrics and crosswalks

 Think tanks and in-house R & D labs and venture capital firms. Uber for X and the Airbnb of Y. Apps and accounts and logins and passwords and usernames and email addresses. Password checkers and security questions and layers of encryption. Password resetting, account deletion, and I Am Not A Robot tests. Cashless and frictionless transactions and recurring payments. Crowdsourcing and funding campaigns and matching donations and anonymous donors. AI and machine learning and visual recognition algorithms. Big Data, petabytes, exabytes. Cloud storage and remote hosting. Software as a service, platform as a service. Proprietary databases, End Users license agreements. Public, open, free. Private, closed, restricted. Biometrics, identity theft, retinal scans.

 Tax haven, tax shelter, tax avoidance schemes. Hedge funds, mutual funds, money market funds, index funds. Volatility index, free trade agreements.

 Block chain, bit ledger, mining, crypto currency.

 Activity trackers, Quantified self, To-do list manager, productivity logging.

 Anomie, doxxing, shaming. Retweets, likes, followers. Facebook suicide. IRL,  FOMO, YOLO. LOL. Chatting, messaging, sharing.

 User handle, Avatar, personalized Emoji, personal encryption key.

 Forums, board, channel. Streaming, on demand, 

** Performance art and Performance text                    :writing:ammerman:
   :PROPERTIES:
   :CREATED:  [2018-01-15 Mon 06:10]
   :END:

 The decentralization of performance art rubs of on writing.

 Text as language with no center, but not necessarily no thread. If anything the opposite. This is hard to do and really, unless you demand a "gaming" level of interaction from the audience, it's really akin to animation and typography, perhaps more than writing or even film-making (in which narrative is churned through a great visual machinery that imposes a kind of superstructure of extra-textual elements. At it's most extreme, it's programming of natural language constructs built up according to some larger architectonic scheme allowing for dynamic generation of content on the fly.

 This may be what imaginative fiction is actually for, as opposed to actually realizing any of this


** Imagine Counterfactuals                                         :ammerman:
   :PROPERTIES:
   :CREATED:  [2018-01-24 Wed 06:14]
   :END:

 Imagine if the world's artists rose up and collectively declared that there was an impending crisis: there was an arts shortage on the horizon, and soon demand for art works was soon going to far outstrip our world's capacity to provide.

 Well of course it would be regarded as an enormous ruse, a joke by some ill-mannered MFA students. Because it's widely known there is no such thing? Or because the argument is, on its face, ridiculous. Art is not, by its nature, something that takes part in the ordinary exchanges of goods and services by which people satisfy their ever-changing needs and wants. 

 That is, there is no plausible economic argument that exists for why "art" is something that might be in short supply.

 According to Hannah Arendt's The Human Condition, this is because it stands outside of these things. But all is not well, because it does not simply follow that there livelihoods of people who regard themselves as artists are secure. In fact, the illusion of security only occasionally gets clouded over, making it appear that there could be compelling reasons to choose to devote one's efforts to stepping outside the existing patterns of economic exchange that are the primary drivers of many if not most major political questions today.

 But self-delusion is a powerful force, especially when enabled by the monoliths of institutional learning that promise to provide training to all worthy individuals, demand be damned.

 Of course, this is not an argument that people do not value "the arts." Or rather, that some people do not feel pressured to preemptively declare their belief in the value of the arts.

 But what art? And made by whom? And for what purpose? And owned and controlled by whom, and distrubuted by what official or unofficial channels? And for what costs? And made with what tools, consisting of what materials, requiring what kind of interaction, engagement or commitment? And sanctioned by what priesthood?

 But what of the argument made that we need more scientists? More engineers? The economic explanation here seems to hold much more weight, and even the political arguments seem more and more exigent. Impending environmental apocalypses surely will require "new and innovative solutions." And members of post-industrial societies will surely need more creative and hand-held or wearable or subcutaneous ways to insulate themselves off from the unfortunate uncertainties that beset the less economically advanced nations.

 But all of this should rightfully sound dubious, as I have sloppyily constructed it. There is simply so much that remains out of any one individual's control that trying to anticipate the collective outcomes of 5 billion such people's actions is a fool's errand.

 And yet it is precisely what we are tasked with doing. That is, what rational thinkers are tasked with. That is, what scientists are best at.

 There is very quickly a reductio ad absurdum waiting for anyone lazy and unquestioning enough to entertain plausible if casual thinking.

 But to argue that the biggest problems that face the world today will demand scientific answers seems to me problematic. To begin with, the conflicts of interest are patent, but do not seem the least bit troubling. Google is dedicated to making the world a better place. By providing "solutions" to our educational travails. And by developing more engineers that could then be hired by them.

 We can become so enchanted with craftily constructed arguments and our own need to be self-deluded that we forget that Google and EVERY other tech company exists not because of some benevolent, world-healing desire but rather to satisfy shareholders demands.



** Pro stem arguments                                              :ammerman:
   :PROPERTIES:
   :CREATED:  [2018-01-25 Thu 21:04]
   :END:

 What's missing

 What's the  understanding of the current status of our society's relationship with technology? And what assumptions are made about how that will change? What is normative and what is predictive? What can and cannot be known for certain?

** Glut of art argument                                            :ammerman:
   :PROPERTIES:
   :CREATED:  [2018-01-26 Fri 17:02]
   :END:

 At best, this argument is facile and lazy.

 At worst, it is poor, even disingenuous, if not downright harmful.

** What do I want to say?                                          :ammerman:
   :PROPERTIES:
   :CREATED:  [2018-01-26 Fri 22:49]
   :END:

 What is the argument I am trying to make? Is it about what we should value generally? Or just in education? And education at what level? K-12 or beyond? Is this about public education? Is this about the role of art-making in public education in this technological age? Is it about science? Or about reasoning more generally? Is it about trying to influence the process by which society valuates the knowledge that comes from artistic experience, either making or otherwise studying, or even simply encountering?

 Is it merely to offer up the possibility that training in and study of the arts, or particular elements of artistic experience, need not be considered at best extra-curricular, while more and more effort and resources are devoted to reforms that focus on "critical thinking," provided that thinking is unfailing left-brain and linear. And to in fact show that "technology" can be deployed in the midst of artistic training that might "satisfy everyone," whatever that would actually look like.

 Is art-making recognized as a valid form of "knowledge-making," or does it depend on the kind of art? On the artist's intentions? Does the knowledge that artists bring to bear make any contributions to the "sum of human knowledge," in, say, the way that science purports to be "getting closer to the Truth?"

 If we want to start proposing that artists' contributions are worthwhile, as both cultural and intellectual artifacts, we are forced to consider the very terms of our assertions.

 Specifically, consider the way that I'm approaching this. Trying to put all in one document, the linguistic content of what I'm saying, some kind of artistic undertaking to illustrate or at least reflect and refract some of the themes and then of course the very code that I use to generate the art work and transform the raw materials in real time, as if in live performance.

 What do I have against the acronym (as it will be referred to henceforth)?
 It is uninspired, alienating, facile and redundant and now trendy. Some science educators wouldn't bat an eye at most of these accusations, especially the latter--who wouldn't want to go from being the epitome of dorkiness (the school Science fair) to almost, ya know, cool.

 But really, apart from these things, it is worth paying attention to the context, that little "humanizing" characteristic that scientists would love to escape from but that pesky little humanists keep bringing up.

 In the context of bold and dramatic assertions that biggest problems we face today require scientific solutions, we would do well to consider what kind of society we are preparing ourselves for. That's right, the 'ol problem of economics.

 Perhaps foremost is the role this surfeit of engineers will play in the growth of automation as driver of cultural and economic and thus political change.

** Pose simple questions anyone might have                         :ammerman:
   :PROPERTIES:
   :CREATED:  [2018-01-27 Sat 23:43]
   :END:

 What is STEM? Where does the term come from, who is using it, and why?

 Why should artists care? How does the ever-rising status of "STEM" affect us? What should we think about the various efforts underway to "reform" K-12 education, especially of the public variety? Is there something we should be doing, either within our artistic practice or simply as good citizens?

 What are the problems with this cultural push away from the arts? What can be done?

 What is Free Software and what should you know about the Free Software movement and more generally, open access and technological freedom-concerned institutions like Creative Commons, Electronic Frontier Foundation and the like? What are the ramifications for artists who may or may not use computers for anything more than email and basic web browsing?

 What role should technology play in both our artistic practices and artistic training more broadly? And what role should the arts play in our society and particularly in our education?

 What is programming and how do computational approaches come in to play in the work of artists today? What role should computers and specifically programming play in our education?

 What is literate programming, what is a text editor? what is live coding and what are executable environments? 

** Economic vs. Epistemic                                          :ammerman:
   :PROPERTIES:
   :CREATED:  [2018-01-28 Sun 10:28]
   :END:

 The argument about artists' livelihoods was overstated and ultimately less important--because how much more threatened can the lives of people who subsist on earnings from artistic work already be--than the matter of cultural and intellectual value.

 The point I would say it's more subtle but more important draws on SICP.
 I would posit that, in addition to the two kinds of only

** The acronym not a problem if                                    :ammerman:
   :PROPERTIES:
   :CREATED:  [2018-02-01 Thu 12:33]
   :END:

 If all it really stood for, as a totem, were "improved science education."

 But it is much more significant than that.

** Pieces of the Puzzle                                            :ammerman:
** STEM attack angle
   :PROPERTIES:
   :CREATED:  [2018-02-07 Wed 20:51]
   :END:

 The question concerning Technology is not just an influential essay by Heidegger. The question is whose technology? Who owns our software? Who owns our browser history? Who has our best interest at heart? How can you say what my best interest is?

** What do we ask if our STEM?
   :PROPERTIES:
   :CREATED:  [2018-02-07 Wed 22:16]
   :END:

 That it be beautiful.
 That it be human
 That it tolerate ambiguity
 That it fill us work awe
 That it allow us to express ourselves however we want

** Finally concluded.
   :PROPERTIES:
   :CREATED:  [2018-02-08 Thu 02:58]
   :END:

 Needs to be explained what benefit there is to this whole art is ambiguous thesis and how it relates to the unambiguous nature of formal language?

** Translations
   :PROPERTIES:
   :CREATED:  [2018-02-08 Thu 04:13]
   :END:

 Take, "I indulge in rich refusals."

 If you want to spell it out, why this is good poetry, you can do so.

 Here's one version. 

 But we will destroy something about it. This is analogous to Schrodinger's Cat experiment. Killing the cat by stating unequivocally what "it means."



